name: apiverve_birthstones
description: Birthstones is a comprehensive lookup API for birthstone information. It returns detailed data about gemstones associated with each birth month, including the primary stone, alternate stones, colors, meanings, and zodiac associations.
version: 1.1.13
homepage: https://apiverve.com/marketplace/birthstones?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/birthstones-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
